config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :abstracts do
    member do
      post 'accept'
      post 'reject'
    end
  end
  resources :students
  resources :staffs
  resources :messages
  resources :groups
  resources :sessions, only: [:new, :create, :destroy]
  get '/signup/staffs', to: 'staffs#signup'
  post '/signup/staffs', to: 'staffs#reset'
  get '/signup/students', to: 'students#signup'
  post '/signup/students', to: 'students#reset'
  get '/signin', to:'sessions#new'
  get '/signout', to: 'sessions#destroy'
  post '/relation', to:  'relation#create'
  resources :relation
  resources :panels_staffs
  resources :staffs do
    member do
      get 'displaystudent'
    end
  end

  resources :staffs do
    resources :progresses
    resources :panel
    resources :messages do
      member do
        post 'accept'
      end
    end
    resources :abstracts
    member do
      get 'notify'
      post 'confirm'
    end
  end
  resources :staffs do
     resources :students do
       resources :progresses
     end
  end
  resources :students do
    resources :projects
    resources :messages
    resources :groups
  end
   resources :students do
     member do
       get 'marksdisplay'
       get 'notify'
     end
   end
   resources :projects

end

app/models/staff.rb
require 'bcrypt'
class Staff < ActiveRecord::Base
  has_many :students,through: :projects
  has_and_belongs_to_many :panels
  has_many :progresses
  has_many :projects
  
  has_many :sender, class_name: "Message", primary_key: "email", foreign_key: "from", dependent: :destroy
  has_many :receiver, class_name: "Message", primary_key: "email", foreign_key: "to", dependent: :destroy
  validates :name, presence: true
  validates :emp_id, presence: true,uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  include BCrypt
  def password
     @password ||= Password.new(password_digest)
  end
  def password=(password_digest)
    @password = Password.create(password_digest)
    self.password_digest = @password
  end

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:edit, :update, :destroy]
  before_filter :admin_user, only: [:create, :new, :update, :destroy, :index]
  before_action :correct_user,only: [:displaystudent]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end
  def signup
    @staff = Staff.new
  end
  def reset
    @staff=Staff.find_by_email(params[:staff][:email])
    if @staff != nil
      respond_to do |format|
        if @staff.update(pass_params)
          format.html { redirect_to signin_path, notice: 'Staff was successfully signed up.' }
          format.json { render :show, status: :ok, location: @staff }
        else
          format.html { redirect_to signup_staffs_path }
          format.json { render json: @staff.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:failure]="sign up failure. Meet Admin"
      respond_to do |format|
      format.html { redirect_to signup_staffs_path}
      format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end
  # GET /staffs/1
  # GET /staffs/1.json
  def show
      @staff = Staff.find(params[:id])
  end
  # GET /staffs/new
  def new
    @staff = Staff.new
  end
  # GET /staffs/1/edit
  def edit
  end
  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)
    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end
  def notify
    @staff=Staff.find(params[:id])
    @received_msg=@staff.receiver
  end
  def confirm
    @staff=Staff.find(params[:id])

  end
  def displaystudent
    @staff=Staff.find(params[:id])
    @students=@staff.students
    respond_to do |format|
      format.xls {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=students.xls"
      }
      format.html { render :displaystudent}
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name, :email, :emp_id)
    end
    def pass_params
      params.require(:staff).permit(:password)
    end
    def correct_user
      @staff= Staff.find(params[:id])
      redirect_to(root_path) unless current_user?(@staff)
    end

end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>
      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :emp_id %><br>
    <%= f.text_field :emp_id %>
  </div>
  <%= hidden_field(:staff, :password, :value => params[:emp_id])%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/staffs/_updateform.html.erb
<div class="row">
<div class="span6 offset3">
<%= form_for(@staff,url: signup_staffs_path, class: "form-horizontal") do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :email, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :email %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :password, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
    <%= f.password_field :password %>
    </div>
  </div>

  <div class="form-group">
      <div class="col-sm-offset-3 col-sm-5">
        <%= f.submit "Sign Up", class: "btn btn-large btn-primary " %>
      </div>
  </div>
  <br>
  <%= link_to "Already User!", signin_path, class: "btn btn-large" %>
<% end %>

app/views/staffs/displaystudent.html.erb
  <form>
            <input type="text" placeholder="Search.." name="search" style={width:50%;}>
            <button type="submit"><i class="fa fa-search"></i></button>
  </form>
  <br>
  <br>
    <%if current_user.admin?%>
       <%=  link_to 'Download as Excel', displaystudent_staff_path(current_user,format: :xls)%>
    <% end %>
  <div class="studentlist">
      <table class="table table-responsive table-striped">
          <thead>
          <tr>
              <th>Student id</th>
              <th>Student name</th>
              <th>Project</th>
              <th></th>
          </tr>
          </thead>
          <tbody>
          <% @students.each do |p| %>
          <tr>
              <td>
              <div class="ui list">
                <span class="item">
                  <b></b>
                   <%=p.reg_no%>
                </span>

              </div>
              </td>
              <td>
               <div class="ui list">
                <span class="item">
                  <b></b>
                   <%=p.name%>
                </span>

              </div>
            </td>
            <td>
            <div class="ui list">
              <span class="item">
                <b>Title: </b>
                 <%=p.project.name%>
              </span><br>
              <span class="item"><b>Description: </b>
                <%=p.project.description%>
              </span>
              </div>
              </td>


              <td>
                <a href= <%= marksdisplay_student_path(id: p.id)%> >
                    Marks of the student
                </a><br>
              </td>
          </tr>

         <% end %>
          </tbody>
      </table>
  </div>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>
<%= render 'form' %>
<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Staffs</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Emp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.name %></td>
        <td><%= staff.email %></td>
        <td><%= staff.emp_id %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

app/views/staffs/new.html.erb
<h1> To upload bunch of staff</h1>
<%= form_for(@staff) do |f| %>
<%= f.file_field :file %><br>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>
<h1>New Staff</h1>
<%= render 'form' %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/notify.html.erb
<h1>Listing messages received by you </h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>From</th>
      <th>Content</th>
      <th>Created at</th>
      <th>Last Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @received_msg.each do |s| %>
      <tr>
        <td><%= s.from %></td>
        <td><%= s.content %></td>
        <td><%= s.created_at%></td>
        <td><%= s.updated_at%></td>
        <td><%= link_to 'Accept',notify_staff_path(@staff.id) %></td>
        <td><%= link_to 'Reject' %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @staff.email %>
</p>

<p>
  <strong>Emp:</strong>
  <%= @staff.emp_id %>
</p>
<% if current_user.admin?%>
<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>
<%end%>

app/views/staffs/signup.html.erb
<%= render 'updateform' %>