config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :abstracts do
    member do
      post 'accept'
      post 'reject'
    end
  end
  resources :students
  resources :staffs
  resources :messages
  resources :groups
  resources :sessions, only: [:new, :create, :destroy]
  get '/signup/staffs', to: 'staffs#signup'
  post '/signup/staffs', to: 'staffs#reset'
  get '/signup/students', to: 'students#signup'
  post '/signup/students', to: 'students#reset'
  get '/signin', to:'sessions#new'
  get '/signout', to: 'sessions#destroy'
  post '/relation', to:  'relation#create'
  resources :relation
  resources :panels_staffs
  resources :staffs do
    member do
      get 'displaystudent'
    end
  end

  resources :staffs do
    resources :progresses
    resources :panel
    resources :messages do
      member do
        post 'accept'
      end
    end
    resources :abstracts
    member do
      get 'notify'
      post 'confirm'
    end
  end
  resources :staffs do
     resources :students do
       resources :progresses
     end
  end
  resources :students do
    resources :projects
    resources :messages
    resources :groups
  end
   resources :students do
     member do
       get 'marksdisplay'
       get 'notify'
     end
   end
   resources :projects

end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :student
  belongs_to :staff
  validates_uniqueness_of :staff_id, :scope => :student_id

  def regno
  end
  def regno=(formreg)
    @stu=Student.find_by_reg_no(formreg)
    @stuid=@stu.id
    self.student_id= @stuid
  end
  def emp_id
  end
  def emp_id=(formemp)
    @sta=Staff.find_by_emp_id(formemp)
    @staid=@sta.id
    self.staff_id= @staid
  end
end

app/controllers/relation_controller.rb
class RelationController < ApplicationController
  def index
    @relations=Relation.all
  end
  def new
    @relation = Relation.new
  end
  def create
    @relation = Relation.new(asso_params)
    respond_to do |format|
      if @relation != nil
        if @relation.save
          @student = Student.find_by_reg_no(params[:relation][:regno])
          @staff = Staff.find_by_emp_id(params[:relation][:emp_id])
          @staff.students<<@student
          format.html { redirect_to staffs_path, notice: 'Allotment was successfully created.' }
          format.json { render :show, status: :created, location: @relation }
        else
          format.html { render :new }
          format.json { render json: @relation.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @relation.destroy
    respond_to do |format|
      format.html { redirect_to relation_path, notice: 'Allotment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
  def asso_params
      params.require(:relation).permit(:regno,:emp_id)
  end
end

app/helpers/relation_helper.rb
module RelationHelper
end

app/views/relation/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Staffs</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Student Name</th>
      <th>Staff Name</th>

    </tr>
  </thead>

  <tbody>
    <% @relations.each do |relation| %>
      <tr>
        <td><%= relation.student.name %></td>
        <td><%= relation.staff.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Allotment', new_relation_path %>

app/views/relation/new.html.erb
<%= form_for(@relation ,url: relation_path) do |f| %>
  <% if @relation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relation.errors.count, "error") %> prohibited relations from being saved:</h2>
      <ul>
      <% @relation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Student_regno %><br>
    <%= f.number_field :regno %>
  </div>

  <div class="field">
    <%= f.label :Staff_emp_id %><br>
    <%= f.text_field :emp_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', relation_path %>