config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :abstracts do
    member do
      post 'accept'
      post 'reject'
    end
  end
  resources :students
  resources :staffs
  resources :messages
  resources :groups
  resources :sessions, only: [:new, :create, :destroy]
  get '/signup/staffs', to: 'staffs#signup'
  post '/signup/staffs', to: 'staffs#reset'
  get '/signup/students', to: 'students#signup'
  post '/signup/students', to: 'students#reset'
  get '/signin', to:'sessions#new'
  get '/signout', to: 'sessions#destroy'
  post '/relation', to:  'relation#create'
  resources :relation
  resources :panels_staffs
  resources :staffs do
    member do
      get 'displaystudent'
    end
  end

  resources :staffs do
    resources :progresses
    resources :panel
    resources :messages do
      member do
        post 'accept'
      end
    end
    resources :abstracts
    member do
      get 'notify'
      post 'confirm'
    end
  end
  resources :staffs do
     resources :students do
       resources :progresses
     end
  end
  resources :students do
    resources :projects
    resources :messages
    resources :groups
  end
   resources :students do
     member do
       get 'marksdisplay'
       get 'notify'
     end
   end
   resources :projects

end

app/controllers/progresses_controller.rb
class ProgressesController < ApplicationController
  before_action :correct_user, only: [:create,:edit,:update]
  def index
    @staff=Staff.find(params[:staff_id])
    @progresses=@staff.progresses
    @students = Student.all
    respond_to do |format|
      format.xls {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=students.xls"
      }
      format.html { render :index}
    end
  end
  def new
    @staff=Staff.find(params[:staff_id])
    @students=Student.all
    @student=@students.find(params[:student_id])
    @progress=@student.progresses.build
  end
  def create
    @staff=Staff.find(params[:staff_id])
    @students=Student.all
    @student=@students.find(params[:student_id])
    @progress=@student.progresses.new(progress_params)
    if @progress.save
        redirect_to staff_student_progress_path(@staff.id,@student.id,@progress.id)
        flash[:success] = "UR MARKS AND COMMENTS ARE Successfully updated"
    else
      flash[:failure] = "try again"
       render 'new'
    end
  end
  def show
    @staff=Staff.find(params[:staff_id])
    @students=Student.all
    @student=@students.find(params[:student_id])
    @progress=Progress.find(params[:id])
  end
  def edit
    @staff=Staff.find(params[:staff_id])
    @students=Student.all
    @student=@students.find(params[:student_id])
    @progress=Progress.find(params[:id])
  end
  def update
    @staff=Staff.find(params[:staff_id])
    @students=Student.all
    @student=@students.find(params[:student_id])
    @progress=Progress.find(params[:id])
    if @progress.update(progress_params)
        redirect_to staff_student_progress_path(staff_id:@staff.id,student_id:@student.id,id:@progress.id)
        flash[:success] = "Your Marks And Comments Are Successfully updated"
    else
      flash[:failure] = "Update failed.Try again"
       render 'edit'
    end
  end
  private
  def progress_params
    params.require(:progress).permit(:marks,:comments,:student_id,:staff_id, :review0, :review1, :review2, :review3, :approved)
  end
  def correct_user
    @staff= Staff.find(params[:staff_id])
    redirect_to(root_path) unless current_user?(@staff)
  end
end

app/helpers/progress_helper.rb
module ProgressHelper
end

app/views/progresses/_form.html.erb
<div id="progress_form">
<%= form_for(@progress,url:staff_student_progresses_path(params[:staff_id],params[:student_id]))do |f| %>
 <%= hidden_field(:progress, :student_id, :value => params[:student_id])%>
 <%= hidden_field(:progress, :staff_id, :value => params[:staff_id])%>
<p><h4>Name:</h4></p>
<p><%= @student.name%></p>
<p><h4>Register Number:</h4></p>
<p><%= @student.reg_no%></p>
<hr>
<h3><b>Enter the marks review wise</b></h3>
<div class="field">
  <strong>REVIEW 0</strong><br>
  <%= f.number_field :review0 %>
</div>
<div class="field">
  <strong>REVIEW 1</strong><br>
  <%= f.number_field :review1 %>
</div>
<div class="field">
  <strong>REVIEW 2</strong><br>
  <%= f.number_field :review2 %>
</div>
<div class="field">
  <strong>REVIEW 3</strong><br>
  <%= f.number_field :review3 %>
</div>
<hr>

<div class="field">
  <%=f.check_box(:approved, {}, true)%><b> Final Approval </b></br>
</div>
<div>
  <p><b>Note: </b>Once approved,the marks cannot be edited later</p>
</div>
 <div class="field">
  <%= f.label :comments%><br>
  <%= f.text_area :comments%>
  </div>

 <div class="actions">
   <%= f.submit "Record ur Opinion"%>
 </div>
<%end%>
</div>

app/views/progresses/edit.html.erb
<div id = "progress_form">
 <%= form_for(@progress,url:staff_student_progress_path(params[:staff_id],params[:student_id],@progress.id))do |f| %>
 <%= hidden_field(:progress, :student_id, :value => params[:student_id])%>
 <%= hidden_field(:progress, :staff_id, :value => params[:staff_id])%>
<p><h4>Name:</h4></p>
<p><%= @student.name%></p>
<p><h4>Register Number:</h4></p>
<p><%= @student.reg_no%></p>
<hr>
<h3><b>Enter the marks review wise</b></h3>
<div class="field">
  <strong>REVIEW 0</strong><br>
  <%= f.number_field :review0 %>
</div>
<div class="field">
  <strong>REVIEW 1</strong><br>
  <%= f.number_field :review1 %>
</div>
<div class="field">
  <strong>REVIEW 2</strong><br>
  <%= f.number_field :review2 %>
</div>
<div class="field">
  <strong>REVIEW 3</strong><br>
  <%= f.number_field :review3 %>
</div>
<hr>
<%if @progress.approved != true%>
<div class="field">
   <%=f.check_box(:approved, {}, true)%><b> Final Approval </b></br>
</div>
<%end%>
<div>
  <p><b>Note: </b>Once approved,the marks cannot be edited later</p>
</div>
 <div class="field">
  <%= f.label :comments%><br>
  <%= f.text_area :comments%>
</div>

 <div class="actions">
   <%= f.submit "Record ur Opinion"%>
 </div>
<%end%>
</div>

app/views/progresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing progresses by you </h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Student Name</th>
      <th>Marks</th>
      <th>Comments</th>
      <th>Created at</th>
      <th>Last Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @progresses.each do |p|  if p!=nil%>
      <tr>
        <td><%= p.student.name %></td>
        <td><b><%= p.marks %></b><br>
            <span><b>Review 0 :</b><%=p.review0.present? ?  p.review0 : "NOT PROVIDED" %></span><br>
            <span><b>Review 1 :</b><%=p.review1.present? ?  p.review1 : "NOT PROVIDED" %></span><br>
            <span><b>Review 2 :</b><%=p.review2.present? ?  p.review2 : "NOT PROVIDED" %></span><br>
            <span><b>Review 3 :</b><%=p.review3.present? ?  p.review3 : "NOT PROVIDED" %></span>
        </td>
        <td><%= p.comments %></td>
        <td><%= p.created_at.in_time_zone("Chennai")%></td>
        <td><%= p.updated_at.in_time_zone("Chennai")%></td>
        <%if p.approved == true%>
          <td><%= link_to 'Show', staff_student_progress_path(p.staff_id,p.student_id,p.id) %></td>
        <%else%>
          <td><%= link_to 'Edit', edit_staff_student_progress_path(p.staff_id,p.student_id,p.id) %></td>
        <%end%>
      </tr>
    <% end end %>
  </tbody>
</table>
<h3>Download student overall mark details</h3>
<%=  link_to 'Download as Excel',staff_progresses_path(current_user,format: :xls)%>
<br>
<br>
<%if current_user.admin?%>
<h1>All progress of your college student </h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Student Name</th>
      <th>Marks</th>
      <th>Comments</th>
      <th>Provided by</th>
      <th>Last Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%if current_user.admin?%>
    <% Progress.all.each do |p|  if p!=nil%>
      <tr>
        <td><%= p.student.name %></td>
        <td><b><%= p.marks %></b><br>
            <span><b>Review 0 :</b><%=p.review0.present? ?  p.review0 : "NOT PROVIDED" %></span><br>
            <span><b>Review 1 :</b><%=p.review1.present? ?  p.review1 : "NOT PROVIDED" %></span><br>
            <span><b>Review 2 :</b><%=p.review2.present? ?  p.review2 : "NOT PROVIDED" %></span><br>
            <span><b>Review 3 :</b><%=p.review3.present? ?  p.review3 : "NOT PROVIDED" %></span>
        </td>
        <td><%= p.comments %></td>
        <td><%= p.staff.name%></td>
        <td><%= p.updated_at.in_time_zone("Chennai")%></td>
        <%if p.approved == true%>
          <td><%= link_to 'Show', staff_student_progress_path(p.staff_id,p.student_id,p.id) %></td>
        <%else%>
          <td><%= link_to 'Edit', edit_staff_student_progress_path(p.staff_id,p.student_id,p.id) %></td>
        <%end%>
      </tr>
    <% end end end%>
  </tbody>
</table>
<br>
<%end%>

app/views/progresses/new.html.erb
 <%= render 'form'%>

app/views/progresses/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Student Name:</strong>
  <%= @student.name %>
</p>
<p>
  <strong>Provided by:</strong>
  <%= @staff.name %>
</p>
<p>
  <strong>Review 0:</strong>
  <%= @progress.review0 %>
</p>

<p>
  <strong>Review 1:</strong>
  <%= @progress.review1 %>
</p>
<p>
  <strong>Review 2:</strong>
  <%= @progress.review2 %>
</p>

<p>
  <strong>Review 3:</strong>
  <%= @progress.review3 %>
</p>

<p>
  <strong>Marks:</strong>
  <%= @progress.marks %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @progress.comments %>
</p>
<%if @progress.approved != true%>
  <td><%= link_to 'Edit', edit_staff_student_progress_path(@staff.id,@student.id,@progress.id)  %></td>
<%end%>

<%= link_to 'Back', staff_path(current_user) %>