config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :abstracts do
    member do
      post 'accept'
      post 'reject'
    end
  end
  resources :students
  resources :staffs
  resources :messages
  resources :groups
  resources :sessions, only: [:new, :create, :destroy]
  get '/signup/staffs', to: 'staffs#signup'
  post '/signup/staffs', to: 'staffs#reset'
  get '/signup/students', to: 'students#signup'
  post '/signup/students', to: 'students#reset'
  get '/signin', to:'sessions#new'
  get '/signout', to: 'sessions#destroy'
  post '/relation', to:  'relation#create'
  resources :relation
  resources :panels_staffs
  resources :staffs do
    member do
      get 'displaystudent'
    end
  end

  resources :staffs do
    resources :progresses
    resources :panel
    resources :messages do
      member do
        post 'accept'
      end
    end
    resources :abstracts
    member do
      get 'notify'
      post 'confirm'
    end
  end
  resources :staffs do
     resources :students do
       resources :progresses
     end
  end
  resources :students do
    resources :projects
    resources :messages
    resources :groups
  end
   resources :students do
     member do
       get 'marksdisplay'
       get 'notify'
     end
   end
   resources :projects

end

app/models/abstract.rb
class Abstract < ActiveRecord::Base
  belongs_to :project

  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true

end

app/controllers/abstracts_controller.rb
class AbstractsController < ApplicationController
  def index
    if params[:staff_id]
      @staff = Staff.find(params[:staff_id])
      @students =  @staff.students
    else
      @abstracts = Abstract.all
    end
  end

  def new
    @abstract = Abstract.new
  end

  def create
    @abstract = Abstract.new(abstract_params)
     if @abstract.save
        redirect_to current_student, notice: "The abstract #{@abstract.name} has been uploaded."
     else
        render "new"
     end
  end
  def show
    @staff = Staff.find(params[:staff_id]) if params[:staff_id]
    @abstract=Abstract.find(params[:id])
    @project=@abstract.project
    @group=@project.group
  end
  def destroy
     @abstract = Abstract.find(params[:id])
     @abstract.destroy
     redirect_to abstracts_path, notice:  "The abstract #{@abstract.name} has been deleted."
  end
  def accept
     @abstract=Abstract.find(params[:id])
     @project=@abstract.project
     respond_to do |format|
      if current_user.admin?
           @abstract.update(final_approval: true)
           format.html { redirect_to @abstract, notice: 'IT iS approved .' }
      end
         if @abstract.update(approved: true,approved_by: @project.staff.name)
           format.html { redirect_to @abstract, notice: 'IT iS approved .' }
           format.json { render :show, status: :ok, location: @abstract }
         else
           format.html { render :show }
           format.json { render json: @abstract.errors, status: :unprocessable_entity }
         end
     end
  end
  def reject
    @abstract=Abstract.find(params[:id])
    @project=@abstract.project
    respond_to do |format|
        if @abstract.update(approved: false)
          format.html { redirect_to @abstract, notice: 'The abstract has been rejected.' }
          format.json { render :show, status: :ok, location: @abstract }
        else
          format.html { render :show }
          format.json { render json: @abstract.errors, status: :unprocessable_entity }
        end
    end
  end
  private
  def abstract_params
    params.require(:abstract).permit(:name, :attachment ,:project_id)
  end
end

app/helpers/abstracts_helper.rb
module AbstractsHelper
end

app/views/abstracts/_render.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">Modal title</h4>
</div>
<div class="modal-body">
  *Modal content comes here*
</div>
<div class="modal-footer">
  <button class="btn btn-primary">Save</button>
</div>

app/views/abstracts/create.html.erb
<h1>Abstracts#create</h1>
<p>Find me in app/views/abstracts/create.html.erb</p>

app/views/abstracts/destroy.html.erb
<h1>Abstracts#destroy</h1>
<p>Find me in app/views/abstracts/destroy.html.erb</p>

app/views/abstracts/index.html.erb
<h1>List of students to approve the abstract</h1>
<br>
<br>
<table class = "table table-bordered table-striped">
  <%if @students!=nil %>
   <thead>.
      <tr>
         <th>StudentName</th>
         <th>Project Name</th>
         <th> </th>
      </tr>
   </thead>

   <tbody>

      <% @students.each do |s| %>
          <% @abstracts = s.project.abstracts if s.project.present? %>
          <% @abstracts.each do |a| %>
          <% if a.approved == nil%>
          <tr>
            <td><%= s.name %></td>
            <td><%= s.project.name %> </td>
            <td><%= link_to 'show',staff_abstract_path(@staff.id,a.id) %></td>
         </tr>
         <%end%>
        <%end%>
      <% end %>

   </tbody>
   <%end%>
   <%if current_user.admin? && params[:staff_id] == nil%>
   <thead>.
      <tr>
         <th>Group Name</th>
         <th>Project Name</th>
         <th>Approved_by </th>
         <th>Abstract Uploaded at</th>
         <th>Abstract Approved at</th>
         <th></th>
      </tr>
   </thead>

   <tbody>
          <% @abstracts.each do |a| %>
            <%@project = a.project%>
            <% if a.approved == true && a.final_approval != true%>
              <tr>
                <td><%= @project.name%></td>
                <td><%= @project.name %> </td>
                <td><%= @project.staff.name %> </td>
                <td><%= a.created_at.in_time_zone("Chennai")%></td>
                <td><%= a.updated_at.in_time_zone("Chennai")%></td>
                <td><%= link_to 'show',a %></td>
             </tr>
           <%end%>
         <%end%>
   </tbody>

   <%end%>
</table>

app/views/abstracts/new.html.erb
<% if !@abstract.errors.empty? %>
   <div class = "alert alert-error">

      <ul>
         <% @abstract.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>

   </div>
<% end %>

<div class = "well">
  <%if current_student.project == nil %>
      <h5 align="center">Form team and Enter project details</h5>
  <% else %>
   <%= form_for @abstract, html: { multipart: true } do |f| %>
      <%= hidden_field(:abstract, :project_id, :value => current_student.project.id)%>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <br>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>

  <% end %>
</div>

app/views/abstracts/show.html.erb
<%= render 'groups/show'%>
<%= render 'projects/show'%>
<h3><%= @abstract.name %></h3>
<h6><b><%= link_to "Download abstract", @abstract.attachment_url %></b></h6>
<%if @abstract.approved == nil%>
<%= button_to "ACCEPT" ,accept_abstract_path(@abstract) %><br>
<%= button_to "REJECT" , reject_abstract_path(@abstract) %>
<%end%>
<%if current_user.admin? && @abstract.approved == true && @abstract.final_approval!=true %>
<h2>Need to be approved from Project Coordinator</h2>
<%= button_to "ACCEPT" ,accept_abstract_path(@abstract) %><br>
<%= button_to "REJECT" , reject_abstract_path(@abstract) %>
<%end%>